USE coursedb;
ALTER TABLE Course
    ADD FOREIGN KEY(Department_Name) REFERENCES Department(Department_Name)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Lecture
    ADD FOREIGN KEY(CourseID) REFERENCES Course(CourseID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY(Semester_Name) REFERENCES Semester(Semester_Name)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Professor
    ADD FOREIGN KEY(Department_Name) REFERENCES Department(Department_Name)
        ON DELETE CASCADE ON UPDATE CASCADE;